version: '3.1'
services:
  web:
    build:
      context: .
      dockerfile: ./Dockerfile_backend
    command: ./manage.py runserver 0.0.0.0:8000
    environment:
      DATABASE_URL: postgres://postgres:1234@db/postgres
    ports:
    - 8000:8000
    volumes:
    - ./backend:/code
    - ./temp/config:/root/.config
    depends_on:
    - db
    - mailcatcher
  frontend:
    build:
      context: .
      dockerfile: ./Dockerfile_frontend
    command: npm start
    volumes:
    - ./frontend:/code
    - ./backend/static/apps:/dist
  db:
    image: postgres:9.6
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    volumes:
    - ./temp/db:/var/lib/postgresql/data
    ports:
    - 5432:5432
  mailcatcher:
    image: schickling/mailcatcher
    ports:
    - 1080:1080


