FROM python:3.6.3
ENV PYTHONUNBUFFERED 1
RUN echo "deb http://packages.cloud.google.com/apt cloud-sdk-jessie main" | tee -a /etc/apt/sources.list.d/google-cloud-sdk.list && curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | apt-key add - && apt-get update && apt-get install -y google-cloud-sdk
RUN mkdir /code
WORKDIR /code
COPY ./backend/requirements.txt /code
RUN pip install -r requirements.txt
COPY ./backend /code
