# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-19 11:58
from __future__ import unicode_literals

import community.models.post
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('body_raw', models.TextField()),
                ('body_html', models.TextField()),
                ('is_published', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='community.Post')),
                ('user', models.ForeignKey(on_delete=models.SET(community.models.post.get_sentinel_user), to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
